#!/bin/bash

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export TZ="${TZ:-UTC}"
export PATH="/snap/bin:$PATH"
export GPG_TTY="$(tty 2>/dev/null || true)"
# Use null keyring in containers; rely on SNAPCRAFT_STORE_CREDENTIALS for store auth.
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
EMAIL="${EMAIL:-your-email@example.com}"
KEY_NAME="${KEY_NAME:-n5pro-key}"
OUTPUT_DIR="${OUTPUT_DIR:-/data}"
REQUIRE_SNAPCRAFT_AUTH="${REQUIRE_SNAPCRAFT_AUTH:-1}"
SNAPCRAFT_AUTH_READY=0
DEVELOPER_ID=""
MODE="${1:-full}"

start_snapd() {
  if [ "$(ps -p 1 -o comm= 2>/dev/null || true)" != "systemd" ]; then
    echo "error: PID 1 is not systemd; recreate container from compose with /sbin/init first" >&2
    exit 1
  fi

  systemctl daemon-reload
  systemctl enable --now snapd.socket
  systemctl start snapd.service

  until snap version >/dev/null 2>&1; do
    sleep 1
  done
}

install_required_tools() {
  apt-get update
  apt-get install -y tzdata snapd squashfuse fuse gnupg

  snap list snapcraft >/dev/null 2>&1 || snap install snapcraft --classic
  snap list ubuntu-image >/dev/null 2>&1 || snap install ubuntu-image --classic
}

ensure_snapcraft_cli() {
  local i
  for i in $(seq 1 20); do
    if command -v snapcraft >/dev/null 2>&1; then
      return
    fi
    if [ -x /snap/bin/snapcraft ]; then
      export PATH="/snap/bin:$PATH"
      if command -v snapcraft >/dev/null 2>&1; then
        return
      fi
    fi
    sleep 1
  done

  echo "error: snapcraft CLI not found in PATH (expected /snap/bin/snapcraft)" >&2
  exit 1
}

configure_snapcraft_auth() {
  if [ -n "${SNAPCRAFT_STORE_CREDENTIALS:-}" ]; then
    echo "using SNAPCRAFT_STORE_CREDENTIALS from environment"
    SNAPCRAFT_AUTH_READY=1
    return
  fi

  if [ -f /data/snapcraft-store-credentials.txt ]; then
    export SNAPCRAFT_STORE_CREDENTIALS
    SNAPCRAFT_STORE_CREDENTIALS="$(cat /data/snapcraft-store-credentials.txt)"
    echo "loaded SNAPCRAFT_STORE_CREDENTIALS from /data/snapcraft-store-credentials.txt"
    SNAPCRAFT_AUTH_READY=1
    return
  fi

  echo "warning: no Snap Store credentials configured; store-auth commands may fail" >&2
}

collect_developer_id() {
  local whoami_out
  whoami_out="$(snapcraft whoami 2>/dev/null || true)"
  DEVELOPER_ID="$(printf '%s\n' "$whoami_out" | awk '/^id:/ {print $2; exit}')"

  if [ -n "$DEVELOPER_ID" ]; then
    echo "snapcraft developer id: $DEVELOPER_ID"
    return
  fi

  if [ "$REQUIRE_SNAPCRAFT_AUTH" = "1" ]; then
    echo "error: unable to read developer id from 'snapcraft whoami'" >&2
    echo "hint: set SNAPCRAFT_STORE_CREDENTIALS in .env or /data/snapcraft-store-credentials.txt and rerun" >&2
    exit 1
  fi

  echo "warning: developer id not available (store auth not configured)" >&2
}

setup_signing_key() {
  if snap keys 2>/dev/null | awk 'NR>1 {print $1}' | grep -qx "$KEY_NAME"; then
    echo "snap key '$KEY_NAME' already exists"
  else
    echo "creating snap signing key '$KEY_NAME'"
    snap create-key "$KEY_NAME"
  fi

  if [ "$SNAPCRAFT_AUTH_READY" -eq 1 ]; then
    if ! snapcraft register-key "$KEY_NAME"; then
      echo "warning: could not register key '$KEY_NAME' (it may already be registered)" >&2
    fi
  elif [ "$REQUIRE_SNAPCRAFT_AUTH" = "1" ]; then
    echo "error: store auth required but missing; cannot register key '$KEY_NAME'" >&2
    exit 1
  else
    echo "warning: key created locally but not registered with Snap Store" >&2
  fi
}

export_secret_key() {
  local out="$OUTPUT_DIR/${KEY_NAME}.asc"
  local snap_gnupg_home="/root/.snap/gnupg"

  mkdir -p "$OUTPUT_DIR"

  local key_arg
  key_arg="$(gpg --homedir "$snap_gnupg_home" --list-secret-keys --with-colons | awk -F: '/^fpr:/ {print $10; exit}')"

  if [ -z "${key_arg:-}" ]; then
    echo "warning: no secret key found in $snap_gnupg_home to export" >&2
    return
  fi

  if ! gpg --homedir "$snap_gnupg_home" --armor --export-secret-keys "$key_arg" > "$out"; then
    echo "error: failed exporting secret key (passphrase may be required)" >&2
    echo "hint: run inside container: gpg --homedir $snap_gnupg_home --armor --export-secret-keys $key_arg > $out" >&2
    exit 1
  fi

  echo "private key exported to $out"
}

export_snap_gnupg_bundle() {
  local tar_out="$OUTPUT_DIR/snap-gnupg.tar"
  local b64_out="$OUTPUT_DIR/snap-gnupg.tar.b64"

  if [ -d /root/.snap/gnupg ]; then
    tar -C /root -cf "$tar_out" .snap/gnupg
    base64 -w0 "$tar_out" > "$b64_out"
    echo "snap gnupg tarball exported to $tar_out"
    echo "snap gnupg base64 exported to $b64_out"
  else
    echo "warning: /root/.snap/gnupg not found; skipping SNAP_GNUPG_TAR_B64 export" >&2
  fi
}

write_secret_summary() {
  local env_out="$OUTPUT_DIR/github-secrets.env"

  {
    echo "# GitHub Actions secrets generated by initialize.sh"
    echo "DEVELOPER_ID=$DEVELOPER_ID"
    echo "SIGNING_KEY_NAME=$KEY_NAME"
    echo "# Set SIGNING_KEY from file: $OUTPUT_DIR/${KEY_NAME}.asc"
    echo "# Set SNAP_GNUPG_TAR_B64 from file: $OUTPUT_DIR/snap-gnupg.tar.b64"
  } > "$env_out"

  echo "secret summary written to $env_out"
}

ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
echo "$TZ" > /etc/timezone

install_required_tools
start_snapd
ensure_snapcraft_cli

if [ "$MODE" = "prepare" ]; then
  echo "prepare mode complete: snapd/snapcraft installed and ready"
  echo "next: run 'snapcraft login' and 'snapcraft export-login /data/snapcraft-store-credentials.txt'"
  exit 0
fi

configure_snapcraft_auth
collect_developer_id
setup_signing_key
export_secret_key
export_snap_gnupg_bundle
write_secret_summary

